<?php

/**
 * @file
 * Contains views_film.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_film_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_film module.
    case 'help.page.views_film':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module contenant les vues applicables au type de contenu film') . '</p>';
      return $output;

    default:
  }
}
